### ISSUE TITLE
Minor problem with the output option of 'bpgdec' on macOS and Windows

### ISSUE THREAD

**Issue by Maxcharm** [RenYang-home/HLVC#1]
I was testing the HLVC_video_fast.py with the BasketballPass test on my MacBook when I found that the following error would occur:

File "HLVC_video_fast.py", line 75, in <module>
  F0_com = misc.imread(path_com + 'f' + str(f + 1).zfill(3) + '.png')
 File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/lib/utils.py", line 100, in newfunc
  return func(*args, **kwds)
 File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/misc/pilutil.py", line 164, in imread
  im = Image.open(name)
 File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/Image.py", line 2891, in open
  fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'BasketballPass_com_fast_PSNR_1024/f001.png'

After a brief study on 'bpgdec' command from libbpg on macOS and Windows, I found that their behaviours are different from that on Linux in that the '-o [filename]' option doesn't redirect the output of the decoded frame to the given path, instead it would create result.png as the output file. So when F0_com in line 75 is trying to read from the decoded Frame f001.png in BasketballPass_com_fast_PSNR_1024, the error above would occur.

My suggestion is that on macOS or Windows, rewrite all bpgdec commands as:

1. os.system('bpgdec ' + path_com + str(f + 1).zfill(3) + '.bin')
2. os.system('mv result.png ' +  path_com + 'f' + str(f + 1).zfill(3) + '.png')

**Comment by RenYang-home** [comment]
Thanks a lot for your valuable suggestion. I added a notice to README as follows.

Notice for MacOS and Window users:

In the case that '-o [filename]' doesn't work and it always creates result.png as the output file, please follow the suggestions from Maxcharm to rewrite all BPG decoding commands as

os.system('bpgdec ' + path_com + str(f + 1).zfill(3) + '.bin')
os.system('mv result.png ' + path_com + 'f' + str(f + 1).zfill(3) + '.png')
