### ISSUE TITLE
Could you please release the code of WRQE? 

### ISSUE THREAD

**Issue by reddandelion217** [RenYang-home/HLVC#3]
Hi Author!
I am interested in your paper ,and I want to know the subnetwork WRQE deeply, for your not providing its code ,so I am asking for it , could you please release it?
Thanks a lot!
Best sincerely!

**Comment by RenYang-home** [comment]
We will release WRQE in 1 or 2 months, thanks for the patience. In urgent usage, please refer to QG-ConvLSTM:
Paper: https://arxiv.org/pdf/1903.04596.pdf; Codes: https://github.com/ryangchn/QG-ConvLSTM
The WRQE is an advanced version of QG-ConvLSTM with some differences, but they share the same recurrent cell.

**Comment by reddandelion217** [comment]
OK, Thanks for you reply!

**Comment by RenYang-home** [comment]
Hi, we have released the WRQE codes.
If there's any question or find any bug, please feel free to reopen this issue or create new issues. Thanks
