### ISSUE TITLE
Cannot load checkpoints

### ISSUE THREAD

**Issue by ifeherva** [RenYang-home/HLVC#4]
Tensorflow 1.12 cannot load the checkpoint files because data-00000-of-000001 files are missing.

**Comment by RenYang-home** [comment]
Which folder misses data-00000-of-000001?

**Comment by ifeherva** [comment]
All in the Layer2_P-frame/ folders

**Comment by ifeherva** [comment]
Some Layer3_P as well

**Comment by RenYang-home** [comment]
What folder exactly dosen't have it? I have checked, there are that files.

**Comment by RenYang-home** [comment]
There are that files, like https://drive.google.com/drive/folders/1fONApuCZOCiDJaUjAEW1KjbhYaR05-BB?sort=13&direction=a
Which folder exactly doesn't have?

**Comment by ifeherva** [comment]
You are correct. I downloaded the whole folder via google drive as a single zip and it seems it skipped a bunch of files. I dont understand. Thanks for looking into it.

**Comment by ifeherva** [comment]
Info on the issue: https://support.google.com/drive/thread/4142625?hl=en

**Comment by RenYang-home** [comment]
Hi, I have created another link https://data.vision.ee.ethz.ch/reyang/HLVC_model.zip for models, instead of GoogleDrive. This may solve the problem of downloading.
