### ISSUE TITLE
Getting an error when trying to run the demo code example

### ISSUE THREAD

**Issue by erangil** [RenYang-home/HLVC#5]
Hi,

I have downloaded your code but getting errors while trying to run the code examples as displayed in the readme section.

For example:
python HLVC_video_decoder.py --path_bin BasketballPass_com_slow_PSNR_1024 --python_path BasketballPass --frame 101 --mode PSNR --l 1024 --enh 1

Error:
Traceback (most recent call last):
  File "HLVC_video_decoder.py", line 49, in <module>
    with open(path_com + '/select.bin', "rb") as ff:
FileNotFoundError: [Errno 2] No such file or directory: 'BasketballPass_com_slow_PSNR_1024//select.bin'

Kindly advise how to fix this.
Thanks,
Eran

**Comment by RenYang-home** [comment]
Hi,

Did you encode the video? The encoder has to be run first to encode the video, and then the decoder can decode from the bit-stream. Note that the encoder and decoder must use the same configurations, e.g., slow/fast, PSNR/SSIM, lambda, etc.
