### ISSUE TITLE
PSNR calculation

### ISSUE THREAD

**Issue by mustafaakinyilmaz** [RenYang-home/HLVC#6]
Hi,

Thanks for sharing this amazing work. I have a question about the average PSNR calculation. Do you calculate PSNR values for each frame in each sequence then average them all ie total_psnr / number_of_total_frames? 

Thanks

**Comment by RenYang-home** [comment]
Yes, the PSNR is calculated in the RGB domain on each frame, and then average among all frames by total_psnr / number_of_total_frames
