### ISSUE TITLE
Some questions about calculating DBDR

### ISSUE THREAD

**Issue by ghost** [RenYang-home/HLVC#7]
Thanks for your code. And I am so interested in your work. But I am puzzled about how to calculate DBDR.
When I encode videos with x265 (LDP very fast), as follow:
"ffmpeg (input) -c:v libx265 -preset veryfast -tune zerolatency -x265-params "crf=CRF:keyint=10" output.mkv

ffmpeg -pix_fmt yuv420p -r 60 -s 1920x1080 -i ./Beauty_1920x1080_120fps_420_8bit_YUV.yuv -c:v libx265 -preset veryfast -tune zerolatency -x265-params "crf=15:keyint=10" output.mp4"

The output does not provide psnr/ssim values, just like this.

"
.......
.......
video:117047kB audio:0kB subtitle:0kB other streams:0kB global headers:1kB muxing overhead: 0.005346%
x265 [info]: frame I:     61, Avg QP:16.81  kb/s: 203682.50
x265 [info]: frame P:    540, Avg QP:19.98  kb/s: 83527.84
x265 [info]: Weighted P-Frames: Y:0.0% UV:0.0%
x265 [info]: consecutive B-frames: 100.0% 

encoded 601 frames in 59.61s (10.08 fps), 95723.24 kb/s, Avg QP:19.66
"
Calculating BDBR needs PSNR/SSIM and bit rates. Does any configuration I miss? Or we need to calculate psnr/ssim after coding.
So, could you tell me how to calculate DBDR in detail?

**Comment by RenYang-home** [comment]
Calculating BDBR needs at least four pairs of (bpp, PSNR/SSIM), please first google what is BDBR and how to calculate.

**Comment by ghost** [comment]
Ok, I knew this. Before calculating the BDBR, we need to get psnr/ssim values. I mean how to calculate psnr/ssim. I used ffmpeg to calculate PNSR and SSIM after decoding the stream, as follows:
"
 ffmpeg -pix_fmt yuv420p -r 120 -s 1920x1072 -i YachtRide_1920x1072_120fps_420_8bit_YUV_crop.yuv -c:v libx265 -preset veryfast -tune zerolatency -x265-params 'crf=15:keyint=10:verbose=1' steam.mkv
 ffmpeg -i stream.mkv decode.yuv
 ffmpeg -s 1920x1072 -i YachtRide_1920x1072_120fps_420_8bit_YUV_crop.yuv -s 1920x1072 -i decode.yuv  -lavfi psnr="stats_file=psnr.log" -f null -
"
The baseline is important. But it has a little difference with your results shown in data.xls, whether it exists some errors in my code? Is it the same as your code? Could you tell me your method, and I want to address this problem? Thanks for your helping.

**Comment by RenYang-home** [comment]
We calculate PSNR/SSIM in the RGB domain. We first save all frames to png images, and then calculate PSNR/SSIM. Also note that different ffmpeg versions will lead to a bit different compression results. So I think you could compress and evaluate in your own way, just ensure that all compared methods are calculated in a same manner. ——Ren Yanghttps://renyang-home.github.io/Doctoral studentComputer Vision Laboratory | ETH ZürichSternwartstrasse 7 | ETF D 114.2 | 8092 Zürich, Switzerland-------- 原始邮件 --------发件人： ppingz ***@***.***>日期： 2021年5月1日周六 18:05收件人： RenYang-home/HLVC ***@***.***>抄送： Ren Yang ***@***.***>, State change ***@***.***>主    题： Re: [RenYang-home/HLVC] Some questions about calculating DBDR (#7)
Ok, I knew this. Before calculating the BDBR, we need to get psnr/ssim values. I mean how to calculate psnr/ssim. I used ffmpeg to calculate PNSR and SSIM after decoding the stream, as follows:
"
ffmpeg -pix_fmt yuv420p -r 120 -s 1920x1072 -i YachtRide_1920x1072_120fps_420_8bit_YUV_crop.yuv -c:v libx265 -preset veryfast -tune zerolatency -x265-params 'crf=15:keyint=10:verbose=1' steam.mkv
ffmpeg -i stream.mkv decode.yuv
ffmpeg -s 1920x1072 -i YachtRide_1920x1072_120fps_420_8bit_YUV_crop.yuv -s 1920x1072 -i decode.yuv  -lavfi psnr="stats_file=psnr.log" -f null -
"
The baseline is important. But it has a little difference with your results shown in data.xls, whether it exists some errors in my code? Is it the same as your code? Could you tell me your method, and I want to address this problem? Thanks for your helping.

**Comment by ghost** [comment]
Okay, thanks for your helping again.
